name: Deploy Prisma Migrations

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm install

            - name: Run Prisma Migrations
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
              run: npx prisma migrate deploy

            - name: Verify Prisma Migrations
              run: npx prisma migrate status
